version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./common.env
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  mysql:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - ./common.env
    volumes:
      - ./mysql-volume:/var/lib/mysql
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/etc/mongo
